import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.database.session import SessionLocal, engine
from app.main import app

#from app.api.dependencies.auth import require_api_key
from app.security.dependencies import get_current_principal


@pytest.fixture(autouse=True)
def bypass_security_dependencies():
    """
    Globally mock out all authentication and authorization blocks
    across the entire API test workspace dynamically.
    """
    # 1. Bypass explicit, static dependencies
    # app.dependency_overrides[require_api_key] = lambda: None
    app.dependency_overrides[get_current_principal] = lambda: {
        "id": "ci-test-user",
        "email": "test@example.com",
        "role": "admin"
    }

    # 2. Dynamically bypass factory dependencies like require_role
    # We inspect the routes to find the specific inner closures generated by require_role
    for route in app.routes:
        if hasattr(route, "dependencies"):
            for dep in route.dependencies:
                # Identify the require_role inner function by checking its module/name
                func = dep.dependency
                if hasattr(func, "__qualname__") and "require_role" in func.__qualname__:
                    app.dependency_overrides[func] = lambda: None

    yield

    # Clean up and reset overrides cleanly after each test finishes
    app.dependency_overrides.clear()


@pytest.fixture
def client() -> TestClient:
    """
    Provide a FastAPI test client.
    """
    return TestClient(app)


@pytest.fixture
def sample_submission_id() -> str:
    """
    Provide a reusable sample external submission identifier.
    """
    return "submission-uuid-123"


@pytest.fixture
def db_session() -> Session:
    """
    Provide an isolated PostgreSQL session for integration tests.
    """
    connection = engine.connect()
    transaction = connection.begin()
    session = SessionLocal(bind=connection)

    try:
        yield session
    finally:
        session.close()
        transaction.rollback()
        connection.close()
