"""create initial monitoring schema

Revision ID: 2e88d8aa38f4
Revises: 
Create Date: 2026-08-24 22:06:19.345499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e88d8aa38f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_officers',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_field_officers_external_id'), 'field_officers', ['external_id'], unique=True)
    op.create_table('locations',
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('lga', sa.String(length=100), nullable=False),
    sa.Column('community', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='ck_locations_valid_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_locations_valid_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_state_lga_community', 'locations', ['state', 'lga', 'community'], unique=False)
    op.create_table('programs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=True)
    op.create_table('raw_submissions',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_submission_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_submissions_external_submission_id'), 'raw_submissions', ['external_submission_id'], unique=True)
    op.create_index(op.f('ix_raw_submissions_processing_status'), 'raw_submissions', ['processing_status'], unique=False)
    op.create_index('ix_raw_submissions_source_external_id', 'raw_submissions', ['source', 'external_submission_id'], unique=False)
    op.create_table('activities',
    sa.Column('raw_submission_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('field_officer_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_title', sa.String(length=255), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='completed', nullable=False),
    sa.Column('target_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actual_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('male_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('female_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('youth_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('adult_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_participants >= 0', name='ck_activities_non_negative_actual_participants'),
    sa.CheckConstraint('adult_participants >= 0', name='ck_activities_non_negative_adult_participants'),
    sa.CheckConstraint('female_participants >= 0', name='ck_activities_non_negative_female_participants'),
    sa.CheckConstraint('male_participants + female_participants = actual_participants', name='ck_activities_gender_total_matches_actual'),
    sa.CheckConstraint('male_participants >= 0', name='ck_activities_non_negative_male_participants'),
    sa.CheckConstraint('target_participants >= 0', name='ck_activities_non_negative_target_participants'),
    sa.CheckConstraint('youth_participants + adult_participants = actual_participants', name='ck_activities_age_total_matches_actual'),
    sa.CheckConstraint('youth_participants >= 0', name='ck_activities_non_negative_youth_participants'),
    sa.ForeignKeyConstraint(['field_officer_id'], ['field_officers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_submission_id'], ['raw_submissions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_submission_id')
    )
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_field_officer_id'), 'activities', ['field_officer_id'], unique=False)
    op.create_index('ix_activities_location_activity_date', 'activities', ['location_id', 'activity_date'], unique=False)
    op.create_index(op.f('ix_activities_location_id'), 'activities', ['location_id'], unique=False)
    op.create_index('ix_activities_program_activity_date', 'activities', ['program_id', 'activity_date'], unique=False)
    op.create_index(op.f('ix_activities_program_id'), 'activities', ['program_id'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index('ix_activities_status_activity_date', 'activities', ['status', 'activity_date'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('raw_submission_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.String(length=50), server_default='warning', nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='open', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_submission_id'], ['raw_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_quality_issues_raw_submission', 'data_quality_issues', ['raw_submission_id'], unique=False)
    op.create_index(op.f('ix_data_quality_issues_rule_name'), 'data_quality_issues', ['rule_name'], unique=False)
    op.create_index('ix_data_quality_issues_status_severity', 'data_quality_issues', ['status', 'severity'], unique=False)
    op.create_table('program_targets',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=150), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_program_targets_valid_period'),
    sa.CheckConstraint('target_value >= 0', name='ck_program_targets_non_negative_target'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'indicator_name', 'period_start', 'period_end', name='uq_program_target_indicator_period')
    )
    op.create_index('ix_program_targets_program_period', 'program_targets', ['program_id', 'period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_targets_program_period', table_name='program_targets')
    op.drop_table('program_targets')
    op.drop_index('ix_data_quality_issues_status_severity', table_name='data_quality_issues')
    op.drop_index(op.f('ix_data_quality_issues_rule_name'), table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_raw_submission', table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index('ix_activities_status_activity_date', table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_program_id'), table_name='activities')
    op.drop_index('ix_activities_program_activity_date', table_name='activities')
    op.drop_index(op.f('ix_activities_location_id'), table_name='activities')
    op.drop_index('ix_activities_location_activity_date', table_name='activities')
    op.drop_index(op.f('ix_activities_field_officer_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_raw_submissions_source_external_id', table_name='raw_submissions')
    op.drop_index(op.f('ix_raw_submissions_processing_status'), table_name='raw_submissions')
    op.drop_index(op.f('ix_raw_submissions_external_submission_id'), table_name='raw_submissions')
    op.drop_table('raw_submissions')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_locations_state_lga_community', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_field_officers_external_id'), table_name='field_officers')
    op.drop_table('field_officers')
    # ### end Alembic commands ###
